name = "TFF Binnenfort"
descripton = ""Threefold brings important building blocks for our next stage of prosperity. With TFF Binnenfort we want to support local farming possibilities."
type = "1,2,3" 
contact = "Joe Foxton"
url = "https://www.greenedgecloud.com"
