name = "Woodland Farmer Market"
description = "A friend introduced us to ThreeFold and we loved the idea of contributing to a neutral and sustainable internet by becoming farmers, especially after meeting the team. We strongly believe in ThreeFold and the vision of digital freedom. It is amazing to be a part of such a positive, engaged community sharing the same values."
type = "" 
contact = "Anette & Hannah Cordes"
url = ""
