name = "Vienna Cherry Chapter"
description = "The Vienna Cherry Chapter and it's 18 Members became a Threefolf Farmer because we wanted to be part of this exciting decentralized grid."
farmer type = "1,2" 
person in contact = "Wolfgang Wittmer"
url = ""
