name = "Dragon Edge Cloud"
descripton = "ThreeFold represented a rare opportunity to be involved early on in a new technology with enormous potential to grow.The business opportunity is obvious, but it's green and CSR credentials make this more than just a business - it is helping to shape a democratised and decentalised internet for the future."
type = "1,2,3" 
contact = "Colin Baker"
url = "https://www.dragonedgecloud.com"

